Update python to 3.10.* (#83)
* Update python to 3.11.*

* Try lastedt xrootd 5.6.2 supporting python 3.11

* Try to use lastest torch
ERROR: Could not find a version that satisfies the requirement torch<1.13 (from versions: 1.13.0, 1.13.0+cpu, 1.13.1, 1.13.1+cpu, 2.0.0, 2.0.0+cpu, 2.0.1, 2.0.1+cpu)

* Revert "Try to use lastest torch"

This reverts commit 4da039f816cc1bfc1f84e0aeddbfd1042f639803.

* Let's try instead python 3.10.*

* Added cxx-compiler as a dependency, torch is not happy
Fixing subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

* which cli is missing on cc7 image

* Add Almalinux8 image

* Add Almalinux8 image in CI/CD